name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Dependencies
      run: |
        sudo apt-get update -y
        sudo apt-get install -y pkg-config make gcc gdb valgrind vim autoconf automake libtool
        sudo apt-get install -y libssl-dev libjansson-dev check
    - name: Configure
      run: |
        ./configure CFLAGS="-g -O0" LDFLAGS="-lrt"
    - name: Make
      run: make
    - name: Test
      run: make check
    - name: Valgrind
      env:
        CK_FORK: no
      run: |
        valgrind --leak-check=full --error-exitcode=1 --show-possibly-lost=no --read-inline-info=yes --keep-debuginfo=yes --undef-value-errors=no ./test/check_cjose
